DROP TABLE IF EXISTS USER_AUTHORS;
DROP TABLE IF EXISTS BOOKS;

CREATE TABLE USER_AUTHORS (
	ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	USERNAME VARCHAR(50) NOT NULL,
	FIRST_NAME VARCHAR(100) NOT NULL,
	LAST_NAME VARCHAR(100) NOT NULL,
	PASSWORD CHAR(60) NOT NULL
);

CREATE TABLE BOOKS (
	ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	TITLE VARCHAR(150) NOT NULL,
	DESCRIPTION VARCHAR(150) NOT NULL,
	AUTHOR BIGINT NOT NULL,
	COVER_IMAGE VARCHAR(250) NOT NULL,
	PRICE DECIMAL(10, 2) NOT NULL,
	PUBLISH_DATE DATETIME NOT NULL,
	FOREIGN KEY (AUTHOR) REFERENCES USER_AUTHORS(ID)
);

-- Password: anJ?FS6w
INSERT INTO USER_AUTHORS (USERNAME, FIRST_NAME, LAST_NAME, PASSWORD) VALUES('admin', 'Jose Luis', 'Perez Olvera', '$2a$10$CtseeuORmf4ZzOhk1Wr1G.WoaNVxXtVFryXwumJjNqKVIwVeBkRN6');
INSERT INTO USER_AUTHORS (USERNAME, FIRST_NAME, LAST_NAME, PASSWORD) VALUES('author', 'George', 'Lucas', '$2a$10$CtseeuORmf4ZzOhk1Wr1G.WoaNVxXtVFryXwumJjNqKVIwVeBkRN6');
INSERT INTO USER_AUTHORS (USERNAME, FIRST_NAME, LAST_NAME, PASSWORD) VALUES('darthvader', 'Darth', 'Vader', '$2a$10$CtseeuORmf4ZzOhk1Wr1G.WoaNVxXtVFryXwumJjNqKVIwVeBkRN6');

INSERT INTO BOOKS (TITLE, DESCRIPTION, AUTHOR, COVER_IMAGE, PRICE, PUBLISH_DATE) VALUES('My First Book', 'This is the first published book by admin', 1, 'https://www.tonica.la/__export/1618261177521/sites/debate/img/2021/04/12/ewok-star-wars-mono-peligro-extincixn_1.jpg_185051854.jpg', 25, CURRENT_DATE());
INSERT INTO BOOKS (TITLE, DESCRIPTION, AUTHOR, COVER_IMAGE, PRICE, PUBLISH_DATE) VALUES('Star Wars', 'This is the first edition of the Star Wars history.', 2, 'https://i1.wp.com/hipertextual.com/wp-content/uploads/2020/05/hipertextual-star-wars-celebra-may-the-4th-be-with-you-con-extraordinario-video-que-rinde-homenaje-toda-saga-2020581511.jpg?fit=1920%2C1080&ssl=1', 50, CURRENT_DATE());